Katrinabi:
    image: spagobilabs/spagobi:all-in-one
    links:
        - Katrinabidb:db
    ports:
    - 8080:8080/tcp
    environment:
        - WAIT_MYSQL=true
Katrinabi-lb:
    image: rancher/lb-service-haproxy:v0.7.6
    ports:
    - 8080:8080/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
Katrinabidb:
    image: mysql:5.5
    environment:
        - MYSQL_USER=spagobiuser
        - MYSQL_PASSWORD=spagobipassword
        - MYSQL_DATABASE=spagobidb
        - MYSQL_ROOT_PASSWORD=spagobirootpassword