Katrinabi:
    image: spagobilabs/spagobi:fiware
    links:
        - Katrinabidb:db
    ports:
    - 8080:8080/tcp
    environment:
        - WAIT_MYSQL=true
Katrinabi-lb:
    image: rancher/lb-service-haproxy:v0.7.6
    ports:
    - 8080:8080/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
Katrinabidb:
    image: mysql:latest
    environment:
        - MYSQL_USER=Katrinabiuser
        - MYSQL_PASSWORD=Katrinabipassword
        - MYSQL_DATABASE=Katrinabidb
        - MYSQL_ROOT_PASSWORD=Katrinabirootpassword