version: '2'
catalog:
  name: Katrinabi
  version: 0.0.2
  description: Katrinabi
services:
  spagobi-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: tcp
        service: spagobi
        source_port: 8080
        target_port: 8080
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  spagobi:
    scale: 1
    start_on_create: true
    health_check:
          healthy_threshold: 2
          response_timeout: 2000
          port: 8080
          unhealthy_threshold: 3
          interval: 2000
          strategy: recreate

  spagobidb:
    scale: 1
    start_on_create: true
