version: '2'
catalog:
  name: Katrinabi
  version: 0.0.2
  description: Katrinabi
services:
  Katrinabi-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: tcp
        service: Katrinabi
        source_port: 80
        path: 'SpagoBI'
        target_port: 8080
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  Katrinabi:
    scale: 1
    start_on_create: true
    health_check:
          healthy_threshold: 2
          response_timeout: 2000
          port: 8080
          unhealthy_threshold: 3
          interval: 2000
          strategy: recreate

  Katrinabidb:
    scale: 1
    start_on_create: true
    health_check:
          healthy_threshold: 2
          response_timeout: 2000
          port: 3306
          unhealthy_threshold: 3
          interval: 2000
          strategy: recreate