name: Apache Zookeeper
description: |
  (Experimental) Zookeeper cluster 如果有相关版权或者疑问请联系datachina@live.com
version: 3.4.9-rancher2
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
projectURL: https://github.com/rawmind0/alpine-zk
license: 
