version: '2'
services:
  logging-agent:
    privileged: true
    image: registry.cn-hangzhou.aliyuncs.com/niusmallnan/logging-es:v0.1.0
    external_links:
    - ${elasticsearch_source}:elasticsearch
    pid: host
    volumes_from:
    - logging-helper
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
      io.rancher.sidekicks: logging-helper
  logging-helper:
    privileged: true
    image: registry.cn-hangzhou.aliyuncs.com/niusmallnan/logging-helper:v0.1.0
    external_links:
    - ${elasticsearch_source}:elasticsearch
    volumes:
    - /var/lib/docker:/var/lib/docker
    - /var/log/logging-volumes:/var/log/logging-volumes
    - /var/log/logging-containers:/var/log/logging-containers
    - /var/run/docker.sock:/var/run/docker.sock
    pid: host
    labels:
      io.rancher.container.pull_image: always
