name: nextcloud
description: Enterprise File Sync and Share
如果有相关版权或者疑问请联系datachina@live.com
v0.0.2增加nfs存储功能
version: 0.0.2
category: File Synchronisation
projectURL: https://github.com/ellerbrock/rancher-collection

