name: nextcloud
description: Enterprise File Sync and Share 如果有相关版权或者疑问请联系datachina@live.com
version: 0.0.1
category: File Synchronisation
projectURL: https://github.com/ellerbrock/rancher-collection

