version: '2'
services:
  spagobi:
    image: 10.20.0.100:7777/spagobilabs/spagobi:all-in-one
    environment:
      WAIT_MYSQL: 'true'
    links:
    - spagobidb:db
    ports:
    - 8080:8080/tcp
  spagobidb:
    image: 10.20.0.100:7777/mysql:5.5
    environment:
      MYSQL_DATABASE: spagobidb
      MYSQL_PASSWORD: spagobipassword
      MYSQL_ROOT_PASSWORD: spagobirootpassword
      MYSQL_USER: spagobiuser